title: CNRV
description: 关注RISC-V和Chisel以及开源IC和EDA在中国的发展
show_downloads: false
google_analytics: UA-102898438-1
theme: 
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
